export const APPOINTMENT_CREATE_REQUEST = "APPOINTMENT_CREATE_REQUEST";
export const APPOINTMENT_CREATE_SUCCESS = "APPOINTMENT_CREATE_SUCCESS";
export const APPOINTMENT_CREATE_FAIL = "APPOINTMENT_CREATE_FAIL";
export const APPOINTMENT_CREATE_RESET = "APPOINTMENT_CREATE_RESET";

export const APPOINTMENT_UPDATE_REQUEST = "APPOINTMENT_UPDATE_REQUEST";
export const APPOINTMENT_UPDATE_SUCCESS = "APPOINTMENT_UPDATE_SUCCESS";
export const APPOINTMENT_UPDATE_FAIL = "APPOINTMENT_UPDATE_FAIL";
export const APPOINTMENT_UPDATE_RESET = "APPOINTMENT_UPDATE_RESET";
