export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";

export const PROFILE_DELETE_AVAILABILITY_REQUEST =
  "PROFILE_DELETE_AVAILABILITY_REQUEST";
export const PROFILE_DELETE_AVAILABILITY_SUCCESS =
  "PROFILE_DELETE_AVAILABILITY_SUCCESS";
export const PROFILE_DELETE_AVAILABILITY_FAIL =
  "PROFILE_DELETE_AVAILABILITY_FAIL";

export const PROFILE_DELETE_COURSE_REQUEST = "PROFILE_DELETE_COURSE_REQUEST";
export const PROFILE_DELETE_COURSE_SUCCESS = "PROFILE_DELETE_COURSE_SUCCESS";
export const PROFILE_DELETE_COURSE_FAIL = "PROFILE_DELETE_COURSE_FAIL";

export const PROFILE_ADD_AVAILABILITY_REQUEST =
  "PROFILE_ADD_AVAILABILITY_REQUEST";
export const PROFILE_ADD_AVAILABILITY_SUCCESS =
  "PROFILE_ADD_AVAILABILITY_SUCCESS";
export const PROFILE_ADD_AVAILABILITY_FAIL = "PROFILE_ADD_AVAILABILITY_FAIL";
export const PROFILE_ADD_AVAILABILITY_RESET = "PROFILE_ADD_AVAILABILITY_RESET";

export const PROFILE_ADD_COURSE_REQUEST = "PROFILE_ADD_COURSE_REQUEST";
export const PROFILE_ADD_COURSE_SUCCESS = "PROFILE_ADD_COURSE_SUCCESS";
export const PROFILE_ADD_COURSE_FAIL = "PROFILE_ADD_COURSE_FAIL";
export const PROFILE_ADD_COURSE_RESET = "PROFILE_ADD_COURSE_RESET";
