export const STUDENT_GET_COURSES_DEPARTMENTS_REQUEST =
  "STUDENT_GET_COURSES_DEPARTMENTS_REQUEST";
export const STUDENT_GET_COURSES_DEPARTMENTS_SUCCESS =
  "STUDENT_GET_COURSES_DEPARTMENTS_SUCCESS";
export const STUDENT_GET_COURSES_DEPARTMENTS_FAIL =
  "STUDENT_GET_COURSES_DEPARTMENTS_FAIL";

export const STUDENT_SEARCH_TEACHER_REQUEST = "STUDENT_SEARCH_TEACHER_REQUEST";
export const STUDENT_SEARCH_TEACHER_SUCCESS = "STUDENT_SEARCH_TEACHER_SUCCESS";
export const STUDENT_SEARCH_TEACHER_FAIL = "STUDENT_SEARCH_TEACHER_FAIL";

export const STUDENT_UPDATE_AVAILABILITY_FAIL =
  "STUDENT_UPDATE_AVAILABILITY_FAIL";
export const STUDENT_UPDATE_AVAILABILITY_SUCCESS =
  "STUDENT_UPDATE_AVAILABILITY_SUCCESS";
export const STUDENT_UPDATE_AVAILABILITY_REQUEST =
  "STUDENT_UPDATE_AVAILABILITY_REQUEST";
export const STUDENT_UPDATE_AVAILABILITY_RESET =
  "STUDENT_UPDATE_AVAILABILITY_RESET";
