export const STUDENT_GET_COURSES_DEPARTMENTS_REQUEST =
  "STUDENT_GET_COURSES_DEPARTMENTS_REQUEST";
export const STUDENT_GET_COURSES_DEPARTMENTS_SUCCESS =
  "STUDENT_GET_COURSES_DEPARTMENTS_SUCCESS";
export const STUDENT_GET_COURSES_DEPARTMENTS_FAIL =
  "STUDENT_GET_COURSES_DEPARTMENTS_FAIL";

export const STUDENT_SEARCH_TEACHER_REQUEST = "STUDENT_SEARCH_TEACHER_REQUEST";
export const STUDENT_SEARCH_TEACHER_SUCCESS = "STUDENT_SEARCH_TEACHER_SUCCESS";
export const STUDENT_SEARCH_TEACHER_FAIL = "STUDENT_SEARCH_TEACHER_FAIL";

export const STUDENT_UPDATE_AVAILABILITY_FAIL =
  "STUDENT_UPDATE_AVAILABILITY_FAIL";
export const STUDENT_UPDATE_AVAILABILITY_SUCCESS =
  "STUDENT_UPDATE_AVAILABILITY_SUCCESS";
export const STUDENT_UPDATE_AVAILABILITY_REQUEST =
  "STUDENT_UPDATE_AVAILABILITY_REQUEST";
export const STUDENT_UPDATE_AVAILABILITY_RESET =
  "STUDENT_UPDATE_AVAILABILITY_RESET";

export const STUDENT_LIST_APPOINTMENT_REQUEST =
  "STUDENT_LIST_APPOINTMENT_REQUEST";
export const STUDENT_LIST_APPOINTMENT_SUCCESS =
  "STUDENT_LIST_APPOINTMENT_SUCCESS";
export const STUDENT_LIST_APPOINTMENT_FAIL = "STUDENT_LIST_APPOINTMENT_FAIL";

export const STUDENT_CREATE_PROFILE_REQUEST = "STUDENT_CREATE_PROFILE_REQUEST";
export const STUDENT_CREATE_PROFILE_SUCCESS = "STUDENT_CREATE_PROFILE_SUCCESS";
export const STUDENT_CREATE_PROFILE_FAIL = "STUDENT_CREATE_PROFILE_FAIL";
export const STUDENT_CREATE_PROFILE_RESET = "STUDENT_CREATE_PROFILE_RESET";
