export const STUDENT_GET_COURSES_DEPARTMENTS_REQUEST =
  "STUDENT_GET_COURSES_DEPARTMENTS_REQUEST";
export const STUDENT_GET_COURSES_DEPARTMENTS_SUCCESS =
  "STUDENT_GET_COURSES_DEPARTMENTS_SUCCESS";
export const STUDENT_GET_COURSES_DEPARTMENTS_FAIL =
  "STUDENT_GET_COURSES_DEPARTMENTS_FAIL";

export const STUDENT_SEARCH_TEACHER_REQUEST = "STUDENT_SEARCH_TEACHER_REQUEST";
export const STUDENT_SEARCH_TEACHER_SUCCESS = "STUDENT_SEARCH_TEACHER_SUCCESS";
export const STUDENT_SEARCH_TEACHER_FAIL = "STUDENT_SEARCH_TEACHER_FAIL";
