export const TEACHER_PROFILE_REQUEST = "TEACHER_PROFILE_REQUEST";
export const TEACHER_PROFILE_SUCCESS = "TEACHER_PROFILE_SUCCESS";
export const TEACHER_PROFILE_FAIL = "TEACHER_PROFILE_FAIL";

export const TEACHER_PROFILE_DELETE_AVAILABILITY_REQUEST =
  "TEACHER_PROFILE_DELETE_AVAILABILITY_REQUEST";
export const TEACHER_PROFILE_DELETE_AVAILABILITY_SUCCESS =
  "TEACHER_PROFILE_DELETE_AVAILABILITY_SUCCESS";
export const TEACHER_PROFILE_DELETE_AVAILABILITY_FAIL =
  "TEACHER_PROFILE_DELETE_AVAILABILITY_FAIL";

export const TEACHER_PROFILE_DELETE_COURSE_REQUEST =
  "TEACHER_PROFILE_DELETE_COURSE_REQUEST";
export const TEACHER_PROFILE_DELETE_COURSE_SUCCESS =
  "TEACHER_PROFILE_DELETE_COURSE_SUCCESS";
export const TEACHER_PROFILE_DELETE_COURSE_FAIL =
  "TEACHER_PROFILE_DELETE_COURSE_FAIL";

export const TEACHER_PROFILE_ADD_AVAILABILITY_REQUEST =
  "TEACHER_PROFILE_ADD_AVAILABILITY_REQUEST";
export const TEACHER_PROFILE_ADD_AVAILABILITY_SUCCESS =
  "TEACHER_PROFILE_ADD_AVAILABILITY_SUCCESS";
export const TEACHER_PROFILE_ADD_AVAILABILITY_FAIL =
  "TEACHER_PROFILE_ADD_AVAILABILITY_FAIL";
export const TEACHER_PROFILE_ADD_AVAILABILITY_RESET =
  "TEACHER_PROFILE_ADD_AVAILABILITY_RESET";

export const TEACHER_PROFILE_ADD_COURSE_REQUEST =
  "TEACHER_PROFILE_ADD_COURSE_REQUEST";
export const TEACHER_PROFILE_ADD_COURSE_SUCCESS =
  "TEACHER_PROFILE_ADD_COURSE_SUCCESS";
export const TEACHER_PROFILE_ADD_COURSE_FAIL =
  "TEACHER_PROFILE_ADD_COURSE_FAIL";
export const TEACHER_PROFILE_ADD_COURSE_RESET =
  "TEACHER_PROFILE_ADD_COURSE_RESET";

export const APPOINTMENT_LIST_FOR_TEACHER_FAIL =
  "APPOINTMENT_LIST_FOR_TEACHER_FAIL";
export const APPOINTMENT_LIST_FOR_TEACHER_REQUEST =
  "APPOINTMENT_LIST_FOR_TEACHER_REQUEST";
export const APPOINTMENT_LIST_FOR_TEACHER_SUCCESS =
  "APPOINTMENT_LIST_FOR_TEACHER_SUCCESS";
